<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NuGet.Configuration" />
    <PackageReference Include="NuGet.Packaging" />
    <PackageReference Include="NuGet.Protocol" />
    <PackageReference Include="NuGet.Versioning" />
    <PackageReference Include="System.Formats.Asn1" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/CP6.Platform.Release/CP6.Platform.Release.csproj" />
  </ItemGroup>
</Project>
