KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="@@CP6_P09_PROVISIONER_USERNAME@@"
  password="@@CP6_P09_PROVISIONER_PASSWORD@@"
  user_@@CP6_P09_PROVISIONER_USERNAME@@="@@CP6_P09_PROVISIONER_PASSWORD@@"
  user_@@CP6_P09_PUBLISHER_USERNAME@@="@@CP6_P09_PUBLISHER_PASSWORD@@"
  user_@@CP6_P09_RECEIVER_USERNAME@@="@@CP6_P09_RECEIVER_PASSWORD@@"
  user_@@CP6_P09_UNAUTHORIZED_USERNAME@@="@@CP6_P09_UNAUTHORIZED_PASSWORD@@";
};
