apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cp6-p09-local-secret-store
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: "@@CP6_P09_SECRETS_FILE@@"
    - name: nestedSeparator
      value: ":"
    - name: multiValued
      value: "false"
