apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.json
  - serviceaccount-publisher.json
  - serviceaccount-receiver.json
  - serviceaccount-provisioner.json
  - serviceaccount-unauthorized.json
  - profile-configmap.json
  - publisher-deployment.json
  - receiver-deployment.json
  - unauthorized-deployment.json
  - kafka-deployment.json
  - provisioner-job.json
  - publisher-service.json
  - receiver-service.json
  - kafka-service.json
  - publish-component.json
  - subscribe-component.json
  - subscription.json
  - networkpolicy-default-deny.json
  - networkpolicy-dns-egress.json
  - networkpolicy-probe-ingress.json
  - networkpolicy-publisher-kafka.json
  - networkpolicy-receiver-kafka.json
  - networkpolicy-provisioner-kafka.json
