<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>CP6.Platform.Testing</PackageId>
    <Description>Consumer test support for CP6 platform integrations.</Description>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../CP6.Platform.Abstractions/CP6.Platform.Abstractions.csproj" />
    <ProjectReference Include="../CP6.Platform.AspNetCore/CP6.Platform.AspNetCore.csproj" />
    <ProjectReference Include="../CP6.Platform.Contracts/CP6.Platform.Contracts.csproj" />
    <ProjectReference Include="../CP6.Platform.EntityFramework/CP6.Platform.EntityFramework.csproj" />
    <ProjectReference Include="../CP6.Platform.Messaging/CP6.Platform.Messaging.csproj" />
  </ItemGroup>
</Project>
