apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: profile-config.patch.json
    target:
      group: ""
      version: v1
      kind: ConfigMap
      name: p09-runtime-profile
      namespace: cp6-p09-ci
