<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>CP6.Platform.AspNetCore</PackageId>
    <Description>ASP.NET Core integration for CP6 distributed services.</Description>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <ProjectReference Include="../CP6.Platform.Abstractions/CP6.Platform.Abstractions.csproj" />
    <ProjectReference Include="../CP6.Platform.Contracts/CP6.Platform.Contracts.csproj" />
  </ItemGroup>
</Project>
